export const Permission = {
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",
  PRODUCT_READ: "PRODUCT_READ",

  GENRE_CREATE: "GENRE_CREATE",
  GENRE_UPDATE: "GENRE_UPDATE",
  GENRE_DELETE: "GENRE_DELETE",
  GENRE_READ: "GENRE_READ",

  ORDER_READ: "ORDER_READ",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_DELETE: "ORDER_DELETE",

  PROMOTION_CREATE: "PROMOTION_CREATE",
  PROMOTION_UPDATE: "PROMOTION_UPDATE",
  PROMOTION_DELETE: "PROMOTION_DELETE",
  PROMOTION_READ: "PROMOTION_READ",
  PROMOTION_REPORT: "PROMOTION_REPORT",

  CONTENT_UPDATE: "CONTENT_UPDATE",
  CONTENT_READ: "CONTENT_READ",

  CUSTOMER_RESET_PASSWORD: "CUSTOMER_RESET_PASSWORD",
  SUPPORT_TASK: "SUPPORT_TASK",
} as const;

export type PermissionType = (typeof Permission)[keyof typeof Permission];